package com.company;

public enum WebAppEnum {
    WEB_APP, DISPLAY_NAME, LISTENER,LISTENER_CLASS, WELCOME_FILE_LIST,
    WELCOME_FILE, FILTER, FILTER_NAME, FILTER_CLASS, INIT_PARAM,
    PARAM_NAME,PARAM_VALUE, FILTER_MAPPING, URL_PATTERN, DISPATCHER,
    SERVLET, SERVLET_NAME, SERVLET_CLASS, SERVLET_MAPPING, ERROR_PAGE,
    EXCEPTION_TYPE, LOCATION, ERROR_CODE
}
